sudo: required
language: C
services:
- docker
before_install:
- docker info
- docker build -t andrealetto/iideaa-docker .
- docker run -it -d andreaaletto/iideaa-docker /bin/zsh
script:
- docker ps | grep -q andreaaletto/iideaa-docker

