sudo: required

language: C

services:
      - docker

before_install:
    - docker info
    - docker build -t mariobarbareschi/iideaa-docker .
    - docker run -it -d mariobarbareschi/iideaa-docker /bin/bash

#after_success:

script:
    - docker ps | grep -q mariobarbareschi/iideaa-docker
